- hosts: all
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Install common packages
        apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
        with_items:
           - tree
           - aptitude
           - iftop
           - python-apt

      - name: Install Webmin key 
        apt_key: url='http://www.webmin.com/jcameron-key.asc' state=present

      - name: Install Webmin repository
        apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' state=present 

      - name: Install Webmin software
        apt: name=webmin state=present update_cache=true cache_valid_time=600

- hosts: logstash-boxes
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Install WebUpd8 keys
        apt_key: state=present keyserver=keyserver.ubuntu.com id=EEA14886

      - name: Install WebUpd8 repository
        apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present

      - name: Automatically select the Oracle License
        shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
        changed_when: false

      - name: Install Oracle JDK 8 
        apt: name=oracle-java8-installer state=latest update_cache=true cache_valid_time=600

      - name: Set Oracle JDK 8 environment variables
        apt: name=oracle-java8-set-default state=latest update_cache=true cache_valid_time=600

      - name: Install Logstash key 
        apt_key: url='http://packages.elasticsearch.org/GPG-KEY-elasticsearch' state=present

      - name: Install Logstash repository
        apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.4/debian stable main' state=present

      - name: Install Logstash 
        apt: name=logstash state=latest update_cache=true cache_valid_time=600

      - name: Start Logstash 
        service: name=logstash state=restarted 

- hosts: redis-boxes
  sudo: yes
  gather_facts: yes
  tasks:
      - name: Install Redis 
        apt: name=redis-server state=latest update_cache=true cache_valid_time=600

      - name: Allow Redis to listen on all network interfaces
        command: /bin/sed --in-place --expression '/bind 127.0.0.1/s/^/# /' /etc/redis/redis.conf 

      - name: Restart Redis 
        service: name=redis-server state=restarted 

